export const PLAYLISTS = [
  {
    id: "1",
    title: "Chill Vibes",
    trackCount: 12,
    cover: "/images/chill.jpg",
    tracks: [
      {
        id: "1",
        title: "Sunset Lover",
        artist: "Petit Biscuit",
        duration: "3:45",
      },
      {
        id: "2",
        title: "Comptine d'un autre été",
        artist: "Yann Tiersen",
        duration: "2:10",
      },
      { id: "3", title: "Night Owl", artist: "Galimatias", duration: "3:52" },
      {
        id: "4",
        title: "Cold Little Heart",
        artist: "Michael Kiwanuka",
        duration: "4:58",
      },
      { id: "5", title: "Retrograde", artist: "James Blake", duration: "3:43" },
      { id: "6", title: "River", artist: "Leon Bridges", duration: "3:58" },
      { id: "7", title: "Open", artist: "Rhye", duration: "3:37" },
      { id: "8", title: "Cherry Wine", artist: "Hozier", duration: "4:17" },
      {
        id: "9",
        title: "Moon Song",
        artist: "Phoebe Bridgers",
        duration: "3:57",
      },
      { id: "10", title: "Holocene", artist: "Bon Iver", duration: "5:36" },
      {
        id: "11",
        title: "Heartbeats",
        artist: "José González",
        duration: "2:40",
      },
      { id: "12", title: "Berlin", artist: "RY X", duration: "4:30" },
    ],
  },
  {
    id: "2",
    title: "Workout Energy",
    trackCount: 10,
    cover: "/images/workout.jpg",
    tracks: [
      { id: "1", title: "Stronger", artist: "Kanye West", duration: "5:12" },
      { id: "2", title: "Power", artist: "Kanye West", duration: "4:52" },
      { id: "3", title: "Till I Collapse", artist: "Eminem", duration: "4:58" },
      {
        id: "4",
        title: "Can't Hold Us",
        artist: "Macklemore & Ryan Lewis",
        duration: "4:18",
      },
      {
        id: "5",
        title: "Eye of the Tiger",
        artist: "Survivor",
        duration: "4:05",
      },
      {
        id: "6",
        title: "Remember the Name",
        artist: "Fort Minor",
        duration: "3:50",
      },
      { id: "7", title: "Lose Yourself", artist: "Eminem", duration: "5:20" },
      {
        id: "8",
        title: "Believer",
        artist: "Imagine Dragons",
        duration: "3:24",
      },
      {
        id: "9",
        title: "Seven Nation Army",
        artist: "The White Stripes",
        duration: "3:51",
      },
      { id: "10", title: "Boom", artist: "Major Lazer", duration: "2:56" },
    ],
  },
];
